name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Setup Java (IMPORTANT FIX)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: npm ci

      - name: Build Web App
        run: npm run build

      - name: Install Capacitor
        run: npm install @capacitor/cli @capacitor/android

      - name: Add Android platform (safe check)
        run: npx cap add android || true

      - name: Sync Android
        run: npx cap sync android

      - name: Give permission to Gradle
        run: chmod +x android/gradlew

      - name: Build APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TinyTok-APK
          path: android/app/build/outputs/apk/release/*.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: TinyTok-AAB
          path: android/app/build/outputs/bundle/release/*.aab
